services:

  postgres:

    image: postgres:17

    env_file:
      - ../.env

    container_name: cerberus-db

    restart: unless-stopped

    environment:

      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

      - ./init:/docker-entrypoint-initdb.d

volumes:

  postgres_data: